const EMAIL_PROVIDER_KEY = process.env.EMAIL_PROVIDER_KEY;
const SMS_PROVIDER_KEY = process.env.SMS_PROVIDER_KEY;
const PUSH_PROVIDER_KEY = process.env.PUSH_PROVIDER_KEY;

export { EMAIL_PROVIDER_KEY, SMS_PROVIDER_KEY, PUSH_PROVIDER_KEY };